//
//  RecipeSuggestionsSheet.swift
//  StashKeeper
//
//  Presents the recipe suggestions generated by RecipeSuggestionService
//  after the Add Item flow detects enough fresh produce in one session.
//

import SwiftUI

struct RecipeSuggestionsSheet: View {
    let suggestions: [RecipeSuggestion]
    /// True while suggestions are still being generated — used by the
    /// on-demand entry point (sheet presented immediately, before
    /// generation finishes) as opposed to the scan-time flow, where
    /// suggestions only exist once generation has already completed.
    var isLoading: Bool = false
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            Group {
                if isLoading {
                    loadingView
                } else if suggestions.isEmpty {
                    emptyView
                } else {
                    ScrollView {
                        LazyVStack(spacing: 16) {
                            ForEach(Array(suggestions.enumerated()), id: \.offset) { _, suggestion in
                                RecipeCard(suggestion: suggestion)
                            }
                        }
                        .padding()
                    }
                }
            }
            .navigationTitle("Recipe Ideas")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }
            }
        }
    }

    private var loadingView: some View {
        VStack(spacing: 16) {
            Spacer()
            ProgressView().controlSize(.large)
            Text("Checking your stash for ideas…")
                .font(.subheadline)
                .foregroundStyle(.secondary)
            Spacer()
        }
    }

    private var emptyView: some View {
        ContentUnavailableView(
            "No Ideas Right Now",
            systemImage: "fork.knife",
            description: Text("Add some fresh produce or pantry items to get recipe suggestions.")
        )
    }
}

private struct RecipeCard: View {
    let suggestion: RecipeSuggestion
    @State private var isExpanded = false

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack(alignment: .firstTextBaseline) {
                Text(suggestion.title)
                    .font(.headline)
                Spacer()
                if !suggestion.estimatedTime.isEmpty {
                    Label(suggestion.estimatedTime, systemImage: "clock")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            Text(suggestion.description)
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)

            if !suggestion.estimatedCaloriesPerServing.isEmpty {
                Label("\(suggestion.estimatedCaloriesPerServing) kcal / serving", systemImage: "flame")
                    .font(.caption)
                    .foregroundStyle(.orange)
            }

            Button {
                withAnimation(.stashSpring) { isExpanded.toggle() }
            } label: {
                Label(isExpanded ? "Hide recipe" : "Show recipe", systemImage: isExpanded ? "chevron.up" : "chevron.down")
                    .font(.caption.weight(.medium))
            }
            .buttonStyle(.pressScale)

            if isExpanded {
                VStack(alignment: .leading, spacing: 12) {
                    Divider()

                    VStack(alignment: .leading, spacing: 4) {
                        Text("Ingredients")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(.secondary)
                        ForEach(Array(suggestion.ingredients.enumerated()), id: \.offset) { _, ingredient in
                            Text("• \(ingredient)")
                                .font(.subheadline)
                        }
                    }

                    VStack(alignment: .leading, spacing: 6) {
                        Text("Steps")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(.secondary)
                        ForEach(Array(suggestion.steps.enumerated()), id: \.offset) { index, step in
                            HStack(alignment: .top, spacing: 8) {
                                Text("\(index + 1).")
                                    .font(.subheadline.weight(.semibold))
                                    .foregroundStyle(.secondary)
                                Text(step)
                                    .font(.subheadline)
                            }
                        }
                    }
                }
                .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
        .padding(16)
        .glassSurface(cornerRadius: 16)
    }
}
